---
title: "Analysis"
author: "Quinn White"
date: "`r Sys.Date()`"
output: 
  html_document:
    code_folding: hide 
    toc: true
knit: (function(input,...) {
  rmarkdown::render(input,output_dir=here::here("output"))})
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,error=TRUE, warning=FALSE,message=FALSE)


library(tidyverse)
library(here)
library(lmtp)

theme_c <- function(...){ 
   # font <- "Helvetica"   #assign font family up front
  #  font <- "Arial"
    theme_bw() %+replace%    #replace elements we want to change
    
    theme(
      
      #text elements
      plot.title = element_text(             #title
                 #  family = font,            #set font family
                   size = 11,                #set font size
                   face = 'bold',            #bold typeface
                   hjust = .5,
                   vjust = 3),               
      
      plot.subtitle = element_text(          #subtitle
                #   family = font,            #font family
                   size = 10,
                   hjust = .5,
                   face = 'italic',
                   vjust = 3),               #font size
      
      axis.title = element_text(             #axis titles
                #   family = font,            #font family
                   size = 10),               #font size
      
      axis.text = element_text(              #axis text
                #   family = font,            #axis famuly
                   size = 8),
      strip.text = element_text(color="white", size = 9,
                                margin=unit(c(.1,.1,.1,.1), 'cm')),
      strip.background = element_rect(fill = "#363636"),
      # t, r, b, l
      plot.margin = unit(c(1,.5,.5,.5), "cm")
      ) %+replace%
      theme(...)
   
}


```

We use the `lmtp` R package, which has extensive documentation [here](https://beyondtheate.com/10_R_multivariate.html). Theoretical details are in __. 

```{r}

dat <- readRDS(here("data/sim_dat.RDS")) 
# readr::write_csv(dat, "data/sim_dat.csv")


learners <- c(
   "SL.glm",        # logistic regression anchor
 # "SL.glmnet",     # lasso / elastic net
 # "SL.bayesglm",
  # "SL.gam",        # smooth nonlinearities
  "SL.ranger",     # random forest
  "SL.xgboost",     # boosted trees 
  "SL.mean"
)



treat_names <- dat %>%
  select(contains("A")) %>%
  colnames()

treat_names_list <- map(seq(1, length(treat_names), by=2), ~{
  c(treat_names[.x], treat_names[.x+1])
})

L_list <- dat %>%
  select(contains("Y")) %>%
  colnames() %>%
  as.list()

Y_vars <- paste0("Y", 1:length(treat_names_list))
L_vars <- paste0("L", (1:length(treat_names_list) - 1))

time_var_pred <- map2(Y_vars,L_vars, ~{c(.x,.y)})

# L_list[[1]] <- c("Y1", "L0")

length(L_list)
length(treat_names_list)


dat_w_outcome <- dat %>%
  rowwise() %>%
  mutate(Y_sum = sum(c_across(starts_with("Y")), 
                     na.rm = TRUE)) %>%
  ungroup()  

```


```{r no-treat}

d_no_treat <- function(data, a) {
  d1 <- \(x) rep(0, length(x))
  d2 <- \(x) rep(0, length(x))

  out <- list(
    d1(data[[a[1]]]),
    d2(data[[a[2]]])
  )
  
  setNames(out, a)
}

set.seed(123)

model_no_treat <- lmtp_tmle(data = dat_w_outcome, 
                 trt = treat_names_list, 
                 outcome = "Y_sum", 
                 time_vary = time_var_pred,
                 shift = d_no_treat, 
                 mtp = FALSE,
                 outcome_type = "continuous",
                 learners_trt = learners, 
                 learners_outcome = learners, 
                 folds = 1)

saveRDS(model_no_treat, here('data/model_no_treat.RDS'))

```

```{r,eval=FALSE}

model <- lmtp_tmle(data = dat_w_outcome, 
                 trt = treat_names_list, 
                 outcome = "Y_sum", 
                 time_vary = time_var_pred,
                 shift = d_treat_no_delay, 
                 mtp = FALSE,
                 outcome_type = "continuous",
                 learners_trt = learners, 
                 learners_outcome = learners, 
                 folds = 1)



# lmtp_contrast(fit_dtr, fit_MR, ref = fit_CD)

```

```{r,eval=FALSE}

d_no_treat <- function(data, a) {
  d1 <- \(x) rep(0, length(x))
  d2 <- \(x) rep(0, length(x))

  out <- list(
    d1(data[[a[1]]]),
    d2(data[[a[2]]])
  )
  
  setNames(out, a)
}

model <- lmtp_tmle(data = dat_w_outcome, 
                 trt = treat_names_list, 
                 outcome = "Y_sum", 
                 time_vary = L_list,
                # baseline = c("L0"),
                 shift = d_no_treat, 
                 mtp = FALSE,
                 outcome_type = "continuous",
                 learners_trt = learners, 
                 learners_outcome = learners, 
                 folds = 1)

saveRDS(model, here('data/model_no_treat.RDS'))

# lmtp_contrast(fit_dtr, fit_MR, ref = fit_CD)

```

```{r treat-no-delay}

d_treat_no_delay <- function(data, a) {
  # d1 <- \(x) rep(1, length(x))
  d2 <- \(x) rep(0, length(x))

  y_prev <- gsub("_.+$", "", a[1])
  y_prev <- gsub("A", "", y_prev)
  y_prev <- paste0("Y", y_prev)
  
  d1 <- \(x) ifelse(y_prev==1, rep(1,length(y_prev)), 0)


  out <- list(
    d1(data[[y_prev]]),
    d2(data[[y_prev]])
  )
  
  setNames(out, a)
}

model_treat_no_delay <- lmtp_tmle(data = dat_w_outcome, 
                 trt = treat_names_list, 
                 outcome = "Y_sum", 
                 time_vary = time_var_pred,
                 shift = d_treat_no_delay, 
                 mtp = FALSE,
                 outcome_type = "continuous",
                 learners_trt = learners, 
                 learners_outcome = learners, 
                 folds = 1)

saveRDS(model_treat_no_delay, here('data/model_treat_no_delay.RDS'))



```


```{r treat-delay}

d_treat_delay <- function(data, a) {
  d1 <- \(x) rep(1, length(x))
  d2 <- \(x) rep(1, length(x))

  out <- list(
    d1(data[[a[1]]]),
    d2(data[[a[2]]])
  )
  
  setNames(out, a)
}

# maybe include Y1 as part of L? think about this more

model_treat_delay <- lmtp_tmle(data = dat_w_outcome, 
                 trt = treat_names_list, 
                 outcome = "Y_sum", 
                 time_vary = time_var_pred,
                 shift = d_treat_delay, 
                 mtp = FALSE,
                 outcome_type = "continuous",
                 learners_trt = learners, 
                 learners_outcome = learners, 
                 folds = 1)

saveRDS(model_treat_delay, here('data/model_treat_delay.RDS'))



```


# Contrasts



```{r,eval=FALSE}

# compare 
model_no_treat <- readRDS(here('data/model_no_treat.RDS'))
model_treat_no_delay <- readRDS(here('data/model_treat_no_delay.RDS'))
model_treat_delay <- readRDS(here('data/model_treat_delay.RDS'))

# effect of treatment with delay compard to treatment without delay 
lmtp_contrast(model_treat_delay,
              ref=model_treat_no_delay, 
              type = "rr")


```


