---
title: "Simulation"
author: "Quinn White"
date: "`r Sys.Date()`"
output: 
  html_document:
    code_folding: hide 
    toc: true
knit: (function(input,...) {
  rmarkdown::render(input,output_dir=here::here("output"))})
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,message=FALSE, warning=FALSE)

library(tidyverse)
library(here)
theme_c <- function(...){ 
   # font <- "Helvetica"   #assign font family up front
  #  font <- "Arial"
    theme_bw() %+replace%    #replace elements we want to change
    
    theme(
      
      #text elements
      plot.title = element_text(             #title
                 #  family = font,            #set font family
                   size = 11,                #set font size
                   face = 'bold',            #bold typeface
                   hjust = .5,
                   vjust = 3),               
      
      plot.subtitle = element_text(          #subtitle
                #   family = font,            #font family
                   size = 10,
                   hjust = .5,
                   face = 'italic',
                   vjust = 3),               #font size
      
      axis.title = element_text(             #axis titles
                #   family = font,            #font family
                   size = 10),               #font size
      
      axis.text = element_text(              #axis text
                #   family = font,            #axis famuly
                   size = 8),
      strip.text = element_text(color="white", size = 9,
                                margin=unit(c(.1,.1,.1,.1), 'cm')),
      strip.background = element_rect(fill = "#363636"),
      # t, r, b, l
      plot.margin = unit(c(1,.5,.5,.5), "cm")
      ) %+replace%
      theme(...)
   
}


```

# Set-Up 


```{r,eval=FALSE, include=FALSE}


Need to discretize time such that positivity holds but such that we only have one event... Perhaps think about this more  

let Y_k be # depredation events in interval
describe that we must pick coarsening scheme such that 

```


```{r simulation-functions}

get_L_at_k <- function(time_point, dat, n_packs) {
  # L_{k-1}
  L_prev <- dat %>% pull(paste0("L", time_point-1))
  # A_{k}
  A1_prev <- dat %>% pull(paste0("A", time_point, "_1"))
  # Y_{k} 
  Y_prev <- dat %>% pull(paste0("Y", time_point))
  
  # wolves previously - wolves killed + term (adding or subtracting one)
  # accounting for death/birth
  # more likely to be birth if Y_prev was 1 (well fed)
  # term accounting for death/birth more likely to be positive 
  
  prob_birth <- ifelse(Y_prev == 1, .7, .5)
  
  L_new <- L_prev - A1_prev + 2*rbinom(n_packs, size=1, prob_birth) - 1
  
  # if pack is less than 3 already, only stay the same or grow 
  L_new <- ifelse(L_new <= 3, L_prev + 
                  rbinom(n_packs, size=1, prob=.5), 
                  L_new)

  Lname <- paste0("L", time_point)
  
  return(dat %>% 
           bind_cols(tibble(!!Lname := L_new))
         )
}

get_treatment_at_k <- function(time_point, dat, n_packs,
                               intervention=NULL,
                               lambda_0=10) {
  
  # L_{k-1}, Y_{k}
  L_prev <- dat %>% pull(paste0("L", time_point-1))
  Y_prev <- dat %>% pull(paste0("Y", time_point))
  
  # prob_treat <- plogis(-1+ 1*scale(L_prev)) 
  
  # hist(prob_treat)
  
  prob_treat <- plogis(-2 + .7*(L_prev)/sqrt(lambda_0)) 
 

  A11 <- rbinom(n_packs, 
                size=pmin(3, L_prev), 
                # multiplying by another bernoulli to make zero more probable
                prob=prob_treat*rbinom(n_packs,
                                       size=1,
                                       prob=.8))
  
  A11 <- ifelse(Y_prev == 0, 0, A11)
  
  A12 <- rbinom(n_packs, size=1, 
                prob=.5*ifelse(A11 > 0, 1, 0))
  
  if (!is.null(intervention)) {
    assigned <- intervention(A11, A12, Y_prev)
    A11 <- assigned %>% pull(A1)
    A12 <- assigned %>% pull(A2)
  }
  
  name1 <- paste0("A", time_point, "_1")
  name2 <- paste0("A", time_point, "_2")
  
  dat %>% 
    bind_cols(tibble(!!name1 := A11,
         !!name2 := A12))

}


get_outcome_at_k <- function(time_point, dat, n_packs, lambda_0=10) {
  
    # Y_{k-1}
    Y_prev <- dat %>% pull(paste0("Y", time_point-1))
    
    # L_{k-1}
    L_prev <- dat %>% pull(paste0("L", time_point-1))
    
    # A_{(k-1),1}
    A1_prev <- dat %>% pull(paste0("A", time_point-1, "_", 1))
    
    # A_{(k-1),1}
    # 0 if no delay, 1 if delay 
    A2_prev <- dat %>% pull(paste0("A", time_point-1, "_", 2))

    # prob_event <- plogis(
    #   -3.5 +
    #     # more likely to kill if killed before 
    #     .5*ifelse(Y_prev==1, 2, 1)*(L_prev/sqrt(lambda_0)) 
    #     # less likely to kill if lost pack members to intervention
    #     # but this affect is attenuated if there was a treatment delay
    #    )*(.7^A1_prev)*(1.4^A2_prev)
    
    prob_event <- plogis(
      #-2.9 +
      #-2 +
      -.5 +
        # more likely to kill if killed before 
        .4*ifelse(Y_prev==1, 1.1, 1)*(L_prev/sqrt(lambda_0)) 
         - .2*A1_prev*ifelse(A2_prev==1, 0, 1)
        # less likely to kill if lost pack members to intervention
        # but this affect is attenuated if there was a treatment delay
       )
    
    
    # tibble(x=prob_event) %>% ggplot(aes(x=x))+geom_histogram()
    
    Y_new <- rbinom(n_packs, size=1, prob=prob_event)
    Yname <- paste0("Y", time_point)

    dat %>% 
      bind_cols(tibble(
        !!Yname := Y_new))
}



```


```{r,eval=FALSE}

YEARS <- 5
K <- (YEARS*12)/2

#----------------------------------------------------------------
# Baseline covariates: number of wolves in pack at study start 
#----------------------------------------------------------------
n_packs <- 50 
lambda_0 <- 10 
L0 <- rpois(n_packs, lambda_0)

# first depredation event
prob_event <- plogis(-2 + 2*scale(L0)) 

# tibble(x=prob_event) %>%
#   ggplot(aes(x=x)) + geom_histogram()

Y1 <- rbinom(n_packs, size=1, prob=prob_event)
current_dat <- bind_cols(L0=L0, Y1=Y1)


for (i in 1:K) {
  current_dat <- get_treatment_at_k(i, current_dat)
  current_dat <- get_L_at_k(i, current_dat)
  current_dat <- get_outcome_at_k(i+1, current_dat)
}

```

# Simulate Data 

```{r run-simulation}

# intervention must be a function that outputs A1, A2 (assigned treatments) 
# takes in the natural value of treatment (so can be a shift intervention)
run_simulation <- function(years, n_packs, intervention=NULL) {
  
  YEARS <- years
  K <- (YEARS*12)/6
  
  #----------------------------------------------------------------
  # Baseline covariates: number of wolves in pack at study start 
  #----------------------------------------------------------------
  # n_packs <- 50 
  lambda_0 <- 10 
  L0 <- rpois(n_packs, lambda_0)
  
  # first depredation event
  # prob_event <- plogis(-4 + .3*(L0)/sqrt(lambda_0)) 
  prob_event <- plogis(-1.5 + .3*(L0)/sqrt(lambda_0)) 

  # prob_event <- plogis(-2 + 2*scale(L0)) 
  
  # tibble(x=prob_event) %>%
  #   ggplot(aes(x=x)) + geom_histogram()
  
  Y1 <- rbinom(n_packs, size=1, prob=prob_event)
  current_dat <- bind_cols(L0=L0, Y1=Y1)

  for (i in 1:K) {
    current_dat <- get_treatment_at_k(i, current_dat,
                                      n_packs,
                                      intervention=intervention)
    current_dat <- get_L_at_k(i, current_dat, n_packs)
    current_dat <- get_outcome_at_k(i+1, current_dat, n_packs)
  }
  
 # cat("here")
  
  current_dat <- get_treatment_at_k(K+1, current_dat,
                                      n_packs,
                                      intervention=intervention)
  #current_dat <- get_L_at_k(K+1, current_dat, n_packs)

  return(current_dat)

}


```

```{r}

N_YEARS <- 4

set.seed(123)

current_dat <- run_simulation(years=N_YEARS, n_packs=100)

saveRDS(current_dat, here("data/sim_dat.RDS"))

colMeans(current_dat %>% select(contains("Y")))


```

  
# Generate Counterfactuals

```{r}

# no treatment
d_identity <- function(x,y,z) {
  return(tibble(A1=x,
                A2=y))
}

# no treatment
d_no_treat <- function(x,y,z) {
  return(tibble(A1=rep(0, length(x)),
                A2 = rep(0, length(x))))
}

# 1 more wolf is killed, no change in delay 
d_add_dose <- function(x,y,z) {
  return(tibble(A1=ifelse(z==1, x+1,x),
                A2 = y))
}


# number of wolves killed the same, change all to delay
d_delay <- function(x,y,z) {
  return(tibble(A1=x,
                A2 = ifelse(z==1, 1, y)))
}


# number of wolves killed the same, change all to delay
d_no_delay <- function(x,y,z) {
  return(tibble(A1=x,
                A2 = ifelse(z==1, 0, y)))
}

get_counterfactual_mean <- function(years, n_packs, intervention) {
  
  dat <- run_simulation(
    years=years, 
    n_packs=n_packs, 
    intervention = intervention) 

  counterfactual_mean <- dat %>%
    rowwise() %>%
    mutate(Y_sum = sum(c_across(starts_with("Y")), 
                       na.rm = TRUE)) %>%
    pull(Y_sum) %>%
    mean()
  
  return(counterfactual_mean)
}


```

```{r,eval=FALSE}
# 1 more wolf is killed, with delay 
d_dose_1_delay <- function(x,y) {
  return(tibble(A1=rep(1, length(x)),
                A2 = rep(1, length(x))))
}

# shift dose up 
# d_shift_dose_up <- function(x,y) {
#   return(tibble(A1=x+1,
#                 A2 = y))
# }




```

```{r calculate-counterfactual-means}

N_PACKS <- 1e5 

mean_add_dose <- get_counterfactual_mean(
  years = N_YEARS,
  n_packs = N_PACKS,
  intervention = d_add_dose)
  
mean_delay <- get_counterfactual_mean(
  years = N_YEARS,
  n_packs = N_PACKS,
  intervention = d_delay)

mean_no_delay <- get_counterfactual_mean(
  years = N_YEARS,
  n_packs = N_PACKS,
  intervention = d_no_delay)

# mean (no change)
mean_no_change <- get_counterfactual_mean(
  years = N_YEARS,
  n_packs = N_PACKS,
  intervention = d_identity)


mean_no_change
mean_add_dose
mean_add_dose-mean_no_change
mean_delay-mean_no_delay

mean_shift_treatment_up
mean_no_change

truth <- list(mean_no_treat=mean_no_treat,
              mean_treat_no_delay=mean_treat_no_delay,
              mean_treat_delay=mean_treat_delay,
              mean_shift_treatment_up=mean_shift_treatment_up,
              mean_no_change=mean_no_change)

saveRDS(truth, here::here('data/truth_from_counterfactuals.RDS'))

```

## True Treatment Effects

```{r,results='asis'}

truth <- readRDS(here::here('data/truth_from_counterfactuals.RDS'))

cat("* True shift effect:", 
    truth$mean_shift_treatment_up-truth$mean_no_change)
cat("* True treatment effect (no delay):",
    truth$mean_treat_no_delay-truth$mean_no_treat)
cat("* True treatment effect (with delay):", 
    truth$mean_treat_delay-truth$mean_no_treat)


```

```{r,eval=FALSE, include=FALSE}
no_treatment <- run_simulation(
  years=N_YEARS, 
  n_packs=N_PACKS, 
  intervention = d_dose_1_delay) 

mean_no_treatment <- no_treatment %>%
  rowwise() %>%
  mutate(Y_sum = sum(c_across(starts_with("Y")), 
                     na.rm = TRUE)) %>%
  pull(Y_sum) %>%
  mean()




```


# Data Quality Checks  {.tabset}

## Pack Size

```{r}

L_length <- current_dat %>% 
  select(contains("L")) %>%
  ncol()

current_dat %>%
  select(contains("L")) %>%
  pivot_longer(cols=everything()) %>%
  mutate(name = factor(name, 
                       levels=c(paste0("L", 0:L_length)))) %>%
  ggplot(aes(x=value)) +
  geom_histogram() + 
  facet_wrap(~name)+
  theme_c()  +
  labs(title="Distribution of the Pack Size, by Interval")


```



## Wolves Removed Among the Treated


```{r}

counts_of_treatment_among_events <- map_df(1:A_length, ~{
  dat <- current_dat %>%
    select(all_of(c( paste0("A", .x, "_1"), 
                     paste0("A", .x, "_2"),
                     paste0("Y", .x)))) %>%
             group_by(across(everything())) %>%
             summarize(n=n()) %>%
             filter(!if_all(-n,~ .x==0)) %>%
    mutate(time_point=.x)
  colnames(dat) <- c("A1", "A2", "Y", "n", "time_point")
  return(dat)
}) 

counts_of_treatment_among_events %>%
  mutate(A2=factor(A2)) %>%
  ggplot(aes(x=A1, y=n, fill=A2)) +
  geom_bar(stat="identity", position="dodge") +
  facet_wrap(~time_point)

```


```{r}

A_length <- current_dat %>%
  select(starts_with("A") & contains("_1")) %>% 
  ncol()

counts_of_treatment_among_events <- map_df(1:A_length, ~{
  dat <- current_dat %>%
    select(all_of(c( paste0("A", .x, "_1"), 
                     paste0("Y", .x)))) %>%
             group_by(across(everything())) %>%
             summarize(n=n()) %>%
             filter(!if_all(-n,~ .x==0)) %>%
    mutate(time_point=.x)
  colnames(dat) <- c("A", "Y", "n", "time_point")
  return(dat)
})

counts_of_treatment_among_events %>%
  ggplot(aes(x=A, y= n)) +
  geom_bar(stat="identity") +
  facet_wrap(~time_point) +
  labs(x="Wolves Removed",
       title="Wolves Removed Among Those with an Event",
       y="Count") +
  theme_c() 



```

```{r}

counts_of_treatment_among_events <- map_df(1:A_length, ~{
  dat <- current_dat %>%
    select(all_of(c( paste0("A", .x, "_2"), 
                     paste0("Y", .x)))) %>%
             group_by(across(everything())) %>%
             summarize(n=n()) %>%
             filter(!if_all(-n,~ .x==0)) %>%
    mutate(time_point=.x)
  colnames(dat) <- c("A", "Y", "n", "time_point")
  return(dat)
})


counts_of_treatment_among_events %>%
  ggplot(aes(x=A, y= n)) +
  geom_bar(stat="identity") +
  facet_wrap(~time_point) +
  labs(x="Wolves Removed",
       title="Of Instances Where Wolves Were Removed,\nPresence of Delay",
       y="Count") +
  theme_c() 

```


## Proportion of Packs with an Event

```{r, fig.width=11}

Y_length <- current_dat %>%
  select(starts_with("Y")) %>% 
  ncol()

current_dat %>%
  select(contains("Y")) %>%
  reframe(across(everything(),~sum(.x)/length(.x))) %>%
  pivot_longer(cols=everything()) %>%
  mutate(name = factor(name, levels=c(paste0("Y", 1:Y_length))))  %>%
  ggplot(aes(x=name, y=value)) +
  geom_bar(stat="identity")+
  labs(x="Time Point",
       title="Depredation Events",
       y="Proportion of Packs\nthat Had an Event") +
  theme_c() 
```

```{r, eval=FALSE,include=FALSE}

current_dat %>%
  group_by(A1_1, Y1) %>%
  summarize(n=n())


current_dat %>%
  select(starts_with("A") & contains("_1"),
         contains("Y")) %>%
  pivot_longer(cols=everything()) %>%
  mutate(name = factor(name, levels=c(paste0("A", 0:A_length, "_1")))) %>%
  ggplot(aes(x=value, fill=)) +
  geom_histogram() + 
  facet_wrap(~name)+
  theme_c() 



```

